libsass_src: Path libsass to throw detailed e.g. "Too many open files" exception
In Hugo we have had mysterious and hard-to-debug error reports about faliling imports on MacOs for files that's obviously there.

Instead of just failing with a general error, we now throw a more detailed error message. From the Hugo side it looks like:

```
Error: error building site: TOCSS: failed to transform "hb/scss/index.scss" (text/x-scss): "<stream>:1:1": error reading file "/Users/bep/dump/large-site-test/_vendor/github.com/twbs/bootstrap/scss/_functions.scss": Too many open files
```

See https://github.com/gohugoio/hugo/issues/12649